// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQpCKRPOgQvcySuuhTJF7xp0pRz9OjB9M',
    appId: '1:570966993200:web:74a6be23f47d073cb240f5',
    messagingSenderId: '570966993200',
    projectId: 'msimockup-c132d',
    authDomain: 'msimockup-c132d.firebaseapp.com',
    storageBucket: 'msimockup-c132d.firebasestorage.app',
    measurementId: 'G-1MWBX0P1XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe1K_gZrtB9Yd8hNRstjSNwBVXYviXGJM',
    appId: '1:570966993200:android:df0384d09b777f78b240f5',
    messagingSenderId: '570966993200',
    projectId: 'msimockup-c132d',
    storageBucket: 'msimockup-c132d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxpudIJFWjyz61ybIf_majLPO2lbAReTk',
    appId: '1:570966993200:ios:11da6cd79b462563b240f5',
    messagingSenderId: '570966993200',
    projectId: 'msimockup-c132d',
    storageBucket: 'msimockup-c132d.firebasestorage.app',
    iosBundleId: 'com.example.pencatatanInOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxpudIJFWjyz61ybIf_majLPO2lbAReTk',
    appId: '1:570966993200:ios:11da6cd79b462563b240f5',
    messagingSenderId: '570966993200',
    projectId: 'msimockup-c132d',
    storageBucket: 'msimockup-c132d.firebasestorage.app',
    iosBundleId: 'com.example.pencatatanInOut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQpCKRPOgQvcySuuhTJF7xp0pRz9OjB9M',
    appId: '1:570966993200:web:f11e850660556bb9b240f5',
    messagingSenderId: '570966993200',
    projectId: 'msimockup-c132d',
    authDomain: 'msimockup-c132d.firebaseapp.com',
    storageBucket: 'msimockup-c132d.firebasestorage.app',
    measurementId: 'G-X89BC7YZR4',
  );

}